include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - use_super_parameters

analyzer:
  exclude:
    - build/**
    - android/**
    - windows/**
    - linux/**
  plugins:
    - dart_code_metrics

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 10
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
    - example/test/**
  rules:
    - newline-before-return
    - prefer-trailing-comma
    - always-remove-listener
    - avoid-border-all
    - avoid-expanded-as-spacer
    - avoid-unnecessary-setstate
    - prefer-const-border-radius
